CI: Publish releases automatically from tags. (#334)
### What

When we tag a commit with a version number (e.g. `v1.2.34`), a new job
will now:

1. Create a GitHub release (in draft).
2. Populate the release notes automatically from `changelog.md`.
3. Build CLI binaries with the version baked in.
4. Generate the connector metadata using the CLI.
5. Upload the metadata and CLI binaries as assets.

### How

Scripting shenanigans.

There's a new job to make the release, and a script that pulls out the
relevant section from the changelog to build the release notes.

diff --git a/.github/workflows/ship.yaml b/.github/workflows/ship.yaml
--- a/.github/workflows/ship.yaml
+++ b/.github/workflows/ship.yaml
@@ -113,8 +113,8 @@ jobs:
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.BROKEN_BUILD_SLACK_WEBHOOK_URL }}
 
-  build-cli-binary:
-    name: build the CLI binary
+  build-cli-binaries:
+    name: build the CLI binaries
     strategy:
       matrix:
         include:
@@ -130,6 +130,7 @@ jobs:
             target: aarch64-apple-darwin
           - runner: windows-latest
             target: x86_64-pc-windows-msvc
+            extension: .exe
     runs-on: ${{ matrix.runner }}
     env:
       CARGO_BUILD_TARGET: ${{ matrix.target }}
@@ -164,25 +165,73 @@ jobs:
 
       - name: build the CLI
         run: |
+          # If we're on a tag, use the tag name as the release version.
+          if [[ "$GITHUB_REF_TYPE" == 'tag' ]]; then
+            # Ensure that the version specified in Cargo.toml is the same as the tag (with a 'v' prefix).
+            CARGO_VERSION="$(cargo metadata --format-version=1 | jq -r '.packages | .[] | select(.name == "ndc-postgres") | .version')"
+            echo "Git tag: ${GIT_REF_NAME}"
+            echo "Cargo version: ${CARGO_VERSION}"
+
+            if [[ "$GITHUB_REF_NAME" != "v${CARGO_VERSION}" ]]; then
+              echo >&2 "The Git tag is \"${GITHUB_REF_NAME}\", but the version in Cargo.toml is \"${CARGO_VERSION}\"."
+              echo >&2 'These must be the same, with a "v" prefix for the tag. Aborting.'
+              exit 1
+            fi
+            export RELEASE_VERSION="$GITHUB_REF_NAME"
+            echo "RELEASE_VERSION = ${RELEASE_VERSION}"
+          fi
+
           if [[ -n '${{ matrix.linker }}' ]]; then
             TARGET_SCREAMING="$(echo '${{ matrix.target }}' | tr '[:lower:]' '[:upper:]' | tr '-' '_')"
             echo "CARGO_TARGET_${TARGET_SCREAMING}_LINKER"='${{ matrix.linker }}'
             declare "CARGO_TARGET_${TARGET_SCREAMING}_LINKER"='${{ matrix.linker }}'
             export "CARGO_TARGET_${TARGET_SCREAMING}_LINKER"
           fi
+
           echo "Building for target: ${CARGO_BUILD_TARGET}"
           cargo build --release --package=ndc-postgres-cli
 
-      - name: wrap the CLI in a directory
-        run: |
-          mkdir -p release/ndc-postgres-cli-${{ matrix.target }}
-          mv target/${{ matrix.target }}/release/ndc-postgres-cli release/ndc-postgres-cli-${{ matrix.target }}/
+          mkdir -p release
+          mv -v target/${{ matrix.target }}/release/ndc-postgres-cli release/ndc-postgres-cli-${{ matrix.target }}${{ matrix.extension }}
 
       - uses: actions/upload-artifact@v4
         with:
           name: ndc-postgres-cli-${{ matrix.target }}
-          path: release/ndc-postgres-cli-${{ matrix.target }}
+          path: release
           if-no-files-found: error
+
+  release:
+    name: release to GitHub
+    needs:
+      - push-docker-images # not strictly necessary, but if this fails, we should abort
+      - build-cli-binaries
+    runs-on: ubuntu-latest
+    # We release when a tag is pushed.
+    if: startsWith(github.ref, 'refs/tags/v')
+    steps:
+      - uses: actions/checkout@v4
+
+      - uses: actions/download-artifact@v4
+        with:
+          path: release/artifacts
+          merge-multiple: true
+
+      - name: generate a changelog
+        run: |
+          ./scripts/release-notes.py "${GITHUB_REF_NAME}" >> release/notes.md
+
+      - name: generate a connector package
+        run: |
+          chmod +x ./release/artifacts/ndc-postgres-cli-*
+          ./release/artifacts/ndc-postgres-cli-x86_64-unknown-linux-gnu --context=release/package initialize --with-metadata
+          tar vczf release/artifacts/package.tar.gz -C release/package .
+
+      - name: create a draft release
+        uses: ncipollo/release-action@v1
+        with:
+          draft: true
+          bodyFile: release/notes.md
+          artifacts: release/artifacts/*
 
   e2e-testing:
     name: check against end-to-end tests
